### ISSUE TITLE
Doesn't start on linux, unhelpful error message

### ISSUE THREAD

**Issue by YPetremann** [narrowtux/SmartModInserter#1]
When I try to start this tool on linux I get :

```
$ java -jar FactorioModManager-0.2.0.jar 
Exception in Application start method
Jul 29, 2015 11:01:27 PM com.narrowtux.fmm.dirwatch.SimpleDirectoryWatchService run
INFO: Starting file watcher service.
```

And it stop.

**Comment by narrowtux** [comment]
ah that shitty javafx exception collection "service" just omits it. I'll see how I can reenable it and I'll send you another jar you can test.

**Comment by YPetremann** [comment]
I think I've found the problem here ...

Your program crash because I use it on linux and you haven't defined a way to do things when things are not defined, in that case it correspond to this message.

```
 // linux users have to define everything themselves
```

But how ?

I think you should have like factorio a setting file always at a specific position relative to the executable so if it doesn't exist, it would create it and all of the folders needed.
Then it would try to autodetect from common locations (absolute and relative to the executable).
Finally it would ask the user for which directory to use.

**Comment by narrowtux** [comment]
Whenever a path has not been automatically found, the settings window
should appear promting the user to define this.

YPetremann notifications@github.com schrieb am Do., 6. Aug. 2015 um
23:07 Uhr:
